import { ArrowDown, ArrowUp, Plus, Trash2 } from 'lucide-react'
import { useState } from 'react'
import { Button } from '../../components/Button'
import { Modal } from '../../components/Modal'
import { db } from '../../db/database'
import type { Exercise, PracticeSession, SessionExercise } from '../../types'

export function SessionEditor({ session, exercises, onClose }: { session: PracticeSession; exercises: Exercise[]; onClose: () => void }) {
  const [items, setItems] = useState<SessionExercise[]>([...session.exercises].sort((a,b) => a.order-b.order))
  const [adding, setAdding] = useState(false)
  const move = (index: number, delta: number) => { const copy = [...items]; const target = index + delta; if (target < 0 || target >= copy.length) return; [copy[index], copy[target]] = [copy[target], copy[index]]; setItems(copy.map((item, order) => ({ ...item, order }))) }
  return <Modal title="Edit today’s session" onClose={onClose} wide><div className="session-editor"><p>Shape the plan before you begin. Optional work stays optional.</p>{items.map((item, index) => { const exercise = exercises.find((e) => e.id === item.exerciseId); return <div className="editor-row" key={item.id}><div className="editor-order"><button disabled={index===0} onClick={() => move(index,-1)}><ArrowUp/></button><button disabled={index===items.length-1} onClick={() => move(index,1)}><ArrowDown/></button></div><div className="editor-name"><strong>{exercise?.name}</strong><span>{exercise?.category}</span></div><label><span>BPM</span><input type="number" value={item.bpm ?? ''} placeholder="—" onChange={(e) => setItems(items.map((x) => x.id === item.id ? { ...x, bpm: e.target.value ? Number(e.target.value) : undefined } : x))}/></label><label><span>Minutes</span><input type="number" value={item.durationSeconds ? Math.ceil(item.durationSeconds/60) : ''} placeholder="—" onChange={(e) => setItems(items.map((x) => x.id === item.id ? { ...x, durationSeconds: e.target.value ? Number(e.target.value)*60 : undefined } : x))}/></label><label className="check-label"><input type="checkbox" checked={item.optional} onChange={(e) => setItems(items.map((x) => x.id === item.id ? { ...x, optional: e.target.checked } : x))}/><span>Optional</span></label><button className="icon-button danger" onClick={() => setItems(items.filter((x) => x.id !== item.id))}><Trash2/></button></div>})}<div className="editor-add"><Button variant="secondary" icon={<Plus/>} onClick={() => setAdding(!adding)}>Add exercise</Button>{adding && <div className="add-menu">{exercises.filter((exercise) => !items.some((item) => item.exerciseId === exercise.id)).map((exercise) => <button key={exercise.id} onClick={() => { setItems([...items, { id: crypto.randomUUID(), exerciseId: exercise.id, order: items.length, bpm: exercise.bpm, durationSeconds: exercise.durationSeconds, repetitions: exercise.repetitions, optional: exercise.optional }]); setAdding(false) }}><strong>{exercise.name}</strong><span>{exercise.category}</span></button>)}</div>}</div><div className="modal-actions"><Button variant="ghost" onClick={onClose}>Cancel</Button><Button onClick={async () => { await db.sessions.update(session.id, { exercises: items }); onClose() }}>Save plan</Button></div></div></Modal>
}
