import { useLiveQuery } from 'dexie-react-hooks'
import { BookOpen, ChevronRight, Plus, Search } from 'lucide-react'
import { useState } from 'react'
import { Button } from '../components/Button'
import { Modal } from '../components/Modal'
import { PageHeader } from '../components/PageHeader'
import { db } from '../db/database'
import type { Exercise, ExerciseCategory, SkillStatus } from '../types'

const categories: ExerciseCategory[] = ['Warm-up','Timing','Technique','Subdivision','Coordination','Rudiment','Transitions','Internal Pulse','Challenge']
export function ExercisesPage() {
  const exercises = useLiveQuery(() => db.exercises.toArray(), []) ?? []
  const results = useLiveQuery(() => db.results.toArray(), []) ?? []
  const [query,setQuery]=useState(''); const [category,setCategory]=useState('All'); const [selected,setSelected]=useState<Exercise>(); const [creating,setCreating]=useState(false)
  const filtered=exercises.filter((e)=>(category==='All'||e.category===category)&&(e.name.toLowerCase().includes(query.toLowerCase())||e.description.toLowerCase().includes(query.toLowerCase())))
  return <><PageHeader eyebrow="YOUR TOOLKIT" title="Exercises" subtitle="A focused library built around your current training." action={<Button icon={<Plus/>} onClick={()=>setCreating(true)}>Custom exercise</Button>}/><div className="library-tools"><label className="search"><Search/><input placeholder="Search exercises" value={query} onChange={(e)=>setQuery(e.target.value)}/></label><select value={category} onChange={(e)=>setCategory(e.target.value)}><option>All</option>{categories.map((c)=><option key={c}>{c}</option>)}</select></div><div className="exercise-grid">{filtered.map((exercise)=>{const history=results.filter((r)=>r.exerciseId===exercise.id);return <button className="exercise-card" onClick={()=>setSelected(exercise)} key={exercise.id}><div><span className="category-icon"><BookOpen/></span><span className={`status-tag status-tag--${exercise.status.toLowerCase()}`}>{exercise.status}</span></div><span className="eyebrow">{exercise.category.toUpperCase()}</span><h2>{exercise.name}</h2><p>{exercise.description}</p><div className="exercise-card__pattern">{exercise.pattern}</div><footer><span>{exercise.bpm ? `${exercise.bpm} BPM` : 'No fixed tempo'}</span><span>{history.length} session{history.length===1?'':'s'}</span><ChevronRight/></footer></button>})}</div>{selected&&<Modal title={selected.name} onClose={()=>setSelected(undefined)} wide><div className="exercise-detail"><div className="exercise-detail__meta"><span>{selected.category}</span><span>{selected.bpm?`${selected.bpm} BPM`:'No fixed tempo'}</span><span>{selected.difficulty}</span></div><p className="lead">{selected.description}</p><div className="pattern-display"><span>PATTERN</span><strong>{selected.pattern}</strong></div><h3>How to practice</h3><ol>{selected.instructions.map((i)=><li key={i}>{i}</li>)}</ol><h3>Purpose</h3><p>{selected.purpose}</p><label><span>Current status</span><select value={selected.status} onChange={async(e)=>{const status=e.target.value as SkillStatus;await db.exercises.update(selected.id,{status});setSelected({...selected,status})}}>{['New','Developing','Comfortable','Solid'].map((s)=><option key={s}>{s}</option>)}</select></label><div className="modal-actions"><Button onClick={()=>setSelected(undefined)}>Done</Button></div></div></Modal>}{creating&&<CreateExercise onClose={()=>setCreating(false)}/>}</>
}

function CreateExercise({onClose}:{onClose:()=>void}) { const [name,setName]=useState('');const [category,setCategory]=useState<ExerciseCategory>('Technique');const [description,setDescription]=useState('');const [bpm,setBpm]=useState<number|undefined>(); return <Modal title="Create custom exercise" onClose={onClose}><form className="create-form" onSubmit={async(e)=>{e.preventDefault();await db.exercises.add({id:crypto.randomUUID(),name,category,description,instructions:description?[description]:[],purpose:'Personal practice focus.',bpm,difficulty:'Foundation',status:'New',optional:false,custom:true});onClose()}}><label><span>Name</span><input required value={name} onChange={(e)=>setName(e.target.value)} placeholder="e.g. Accent grid"/></label><label><span>Category</span><select value={category} onChange={(e)=>setCategory(e.target.value as ExerciseCategory)}>{categories.map((c)=><option key={c}>{c}</option>)}</select></label><label><span>Suggested BPM</span><input type="number" value={bpm??''} onChange={(e)=>setBpm(e.target.value?Number(e.target.value):undefined)} placeholder="Optional"/></label><label><span>Instructions</span><textarea required rows={4} value={description} onChange={(e)=>setDescription(e.target.value)} placeholder="Keep this short and actionable."/></label><div className="modal-actions"><Button variant="ghost" type="button" onClick={onClose}>Cancel</Button><Button type="submit">Create exercise</Button></div></form></Modal> }
